#!/usr/bin/env python3
"""Regenerate tests/spec_manifest.json from Glean's published OpenAPI specs.

The conformance test (tests/test_spec_conformance.py) must run offline, so it
compares client.py against this committed manifest rather than the live spec.
Run this whenever Glean publishes a spec update:

    python3 tools/refresh_spec_manifest.py          # fetch and rewrite
    python3 tools/refresh_spec_manifest.py --check   # fail if stale (for CI)

This is the only file in the repo that reaches the network, and it is not
imported by the package or the test suite.

Requires PyYAML, which is a tooling dependency only — never a runtime one.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path
from typing import Any, Dict

SPECS = {
    "client": "https://gleanwork.github.io/open-api/specs/final/client_rest.yaml",
    "indexing": "https://gleanwork.github.io/open-api/specs/final/indexing.yaml",
}

# The three base paths the client speaks to, longest first so that
# /rest/api/index is not swallowed by /rest/api.
BASES = [
    ("client", "/rest/api/v1"),
    ("metadata", "/rest/api/index"),
    ("indexing", "/api/index/v1"),
]

MANIFEST = Path(__file__).resolve().parent.parent / "tests" / "spec_manifest.json"
HTTP_METHODS = ("get", "post", "put", "delete", "patch")


def normalise(path: str) -> str:
    """Collapse path parameters so {groupName} and {group} compare equal.

    The spec and the client name their parameters differently; only the shape
    of the path is a contract.
    """
    return re.sub(r"\{[^}]*\}", "{}", path)


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=120) as resp:
        return resp.read().decode("utf-8")


def build() -> Dict[str, Any]:
    try:
        import yaml
    except ImportError:
        sys.exit(
            "refresh_spec_manifest needs PyYAML (a tooling-only dependency):\n"
            "    python3 -m pip install pyyaml"
        )

    surfaces: Dict[str, Dict[str, list]] = {name: {} for name, _ in BASES}
    undocumented: Dict[str, list] = {}
    meta: Dict[str, Any] = {}

    for label, url in SPECS.items():
        doc = yaml.safe_load(fetch(url))
        info = doc.get("info", {})
        meta.setdefault("spec_version", info.get("version"))
        meta.setdefault("spec_commit", info.get("x-source-commit-sha"))

        for raw_path, node in (doc.get("paths") or {}).items():
            methods = sorted(m.upper() for m in (node or {}) if m in HTTP_METHODS)
            for surface, base in BASES:
                if raw_path.startswith(base):
                    rel = normalise(raw_path[len(base):]) or "/"
                    if methods:
                        surfaces[surface][rel] = methods
                    else:
                        # Declared in the spec but carrying no operation. Not the
                        # same as absent: the endpoint exists in the document and
                        # its request schema often still does too, but Glean has
                        # stopped documenting it. Recorded separately so the
                        # conformance test can treat it as a known risk rather
                        # than a hard failure.
                        undocumented.setdefault(surface, []).append(rel)
                    break

    return {
        "_comment": (
            "Generated by tools/refresh_spec_manifest.py. Do not edit by hand. "
            "Paths are relative to each surface's base URL, with path parameters "
            "collapsed to {}."
        ),
        **meta,
        "surfaces": {k: dict(sorted(v.items())) for k, v in surfaces.items()},
        "undocumented": {k: sorted(v) for k, v in sorted(undocumented.items())},
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed manifest is out of date")
    args = ap.parse_args(argv)

    fresh = build()
    counts = {k: len(v) for k, v in fresh["surfaces"].items()}

    if args.check:
        if not MANIFEST.exists():
            print("spec_manifest.json is missing", file=sys.stderr)
            return 1
        current = json.loads(MANIFEST.read_text())
        if (current.get("surfaces") != fresh["surfaces"]
                or current.get("undocumented") != fresh.get("undocumented")):
            print(
                "spec_manifest.json is out of date.\n"
                f"  committed: {current.get('spec_commit')}\n"
                f"  published: {fresh.get('spec_commit')}\n"
                "Refresh it with: python3 tools/refresh_spec_manifest.py",
                file=sys.stderr,
            )
            return 1
        print(f"spec_manifest.json is current ({fresh['spec_commit'][:7]})")
        return 0

    MANIFEST.write_text(json.dumps(fresh, indent=2) + "\n")
    print(f"wrote {MANIFEST.relative_to(Path.cwd()) if MANIFEST.is_relative_to(Path.cwd()) else MANIFEST}")
    print(f"  spec {fresh['spec_version']} @ {(fresh['spec_commit'] or '?')[:7]}")
    for surface, n in counts.items():
        print(f"  {surface:9} {n} paths")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
